/* 0.5.7 2021-12-27 16:37:09 */
var app=new function()
{
    this.name="​Ic​e Crystal​",
    this.version="1",
    this.date="2023",
    this.folder="asset-v1/",
    this.looptime=8e3,
    this.bpm=120,
    this.totalframe=520,
    this.nbpolo=7,
    this.nbloopbonus=4,
    this.bonusloopA=!0,
    this.bonusendloopA=!0,
    this.recmaxloop=23,
    this.recminloop=3,
    this.recmintime=Math.round(this.looptime/1e3)*this.recminloop,
    this.spritepolo="polo-sprite.png",
    this.spritepolotshirt="polo-sprite-tshirt.png",
    this.spritepicto="game-picto.png",
    this.colBck="#001b2c",
    this.col0="#0086d1",
    this.col1="#1b4e91",
    this.col2="#193e6f",
    this.col3="#0d284c",
    this.col4="#0a1c33",
    this.animearray=
    [
        {
            name:"v1_1",
            color:"75D1FA",
            uniqsnd:!0
        },
        {
            name:"v1_2",
            color:"75D1FA",
            uniqsnd:!0
        },
        {
            name:"v1_3",
            color:"75D1FA",
            uniqsnd:!0
        },
        {
            name:"v1_4",
            color:"75D1FA",
            uniqsnd:!0
        },
        {
            name:"v1_5",
            color:"75D1FA",
            uniqsnd:!0
        },
        {
            name:"v1_6",
            color:"57819C",
            uniqsnd:!1
        },
        {
            name:"v1_7",
            color:"57819C",
            uniqsnd:!0
        },
        {
            name:"v1_8",
            color:"57819C",
            uniqsnd:!1
        },
        {
            name:"v1_9",
            color:"57819C",
            uniqsnd:!0
        },
        {
            name:"v1_10",
            color:"57819C",
            uniqsnd:!0
        },
        {
            name:"v1_11",
            color:"808080",
            uniqsnd:!0
        },
        {
            name:"v1_12",
            color:"808080",
            uniqsnd:!1
        },
        {
            name:"v1_13",
            color:"808080",
            uniqsnd:!0
        },
        {
            name:"v1_14",
            color:"808080",
            uniqsnd:!0
        },
        {
            name:"v1_15",
            color:"808080",
            uniqsnd:!1
        },
        {
            name:"v1_16",
            color:"6699BB",
            uniqsnd:!1
        },
        {
            name:"v1_17",
            color:"6699BB",
            uniqsnd:!0
        },
        {
            name:"v1_18",
            color:"6699BB",
            uniqsnd:!1
        },
        {
            name:"v1_19",
            color:"6699BB",
            uniqsnd:!1
        },
        {
            name:"v1_20",
            color:"6699BB",
            uniqsnd:!1
        }
    ],
    this.bonusarray=
    [
        
    ]
};